version: "3.3"
networks:
  app-network:
    driver: bridge


services:
  database:
    image: postgres:11.0-alpine
    networks:
      - app-network
    environment:
      DEBUG: 'false'
    env_file:
      - .env

  app:
    depends_on:
      - database
    networks:
      - app-network
    build:
      context: app
      dockerfile: ./Dockerfile
    command: sh ./app/boot.sh
    env_file:
      - .env
    volumes:
      - static_volume:/app/app/static
    ports:
      - 8000:8000

  nginx:
    depends_on:
      - app
    build: ./nginx
    networks:
      - app-network
    volumes:
      - static_volume:/app/app/static
    ports:
      - 1337:80
    restart: always

volumes:
  static_volume: